import { site } from "@/lib/site";

/**
 * Local-SEO content layer. Drives the practice-area and location landing
 * pages (each statically generated with unique title, H1, body, FAQs, and
 * schema). Single source of truth — edit copy here, routes stay generic.
 */

/** Shared branded social card (generated by app/opengraph-image.tsx). */
export const ogImage = {
  url: "/opengraph-image",
  width: 1200,
  height: 630,
  alt: "NAGA Law Chambers — Advocate S. Nagendra Naik, Anantapur, Andhra Pradesh",
};

export type FaqItem = { q: string; a: string };

export type PracticePage = {
  slug: string;
  practiceId: string;
  navLabel: string;
  metaTitle: string;
  metaDescription: string;
  h1: string;
  lead: string;
  body: string[];
  handles: string[];
  forums: string[];
  faqs: FaqItem[];
  related: string[];
};

export type LocationPage = {
  slug: string;
  city: string;
  metaTitle: string;
  metaDescription: string;
  h1: string;
  lead: string;
  body: string[];
  forums: string[];
  faqs: FaqItem[];
};

const advocate = site.advocate.name;

export const practicePages: PracticePage[] = [
  {
    slug: "revenue-land-lawyer-anantapur",
    practiceId: "revenue-land",
    navLabel: "Revenue & Land",
    metaTitle: "Revenue & Land Lawyer in Anantapur",
    metaDescription:
      "Revenue and land dispute advocate in Anantapur district — ROR corrections, Adangal, mutations, patta disputes, Tahsildar & RDO appeals, AP High Court writs. Call Adv. S. Nagendra Naik.",
    h1: "Revenue & Land Dispute Lawyer in Anantapur",
    lead: "Direct representation in land and revenue matters before the Tahsildar, RDO, Collector, and the Andhra Pradesh High Court — across Anantapur district.",
    body: [
      `Land and revenue record disputes turn on documents and on filing in the correct forum at the correct stage. Advocate ${advocate} handles ROR (Record of Rights) corrections, Adangal/Pahani entries, mutation appeals, patta and title disputes, encumbrance issues, and land acquisition proceedings — with preparation on the underlying records before any appeal or writ is filed.`,
      "Many revenue matters are lost not on merits but on procedure — appealing to the wrong authority, missing limitation, or filing without the supporting record. Cases are assessed first for the right route: a revision before the RDO or Collector, an administrative appeal, or a writ before the High Court at Amaravati.",
      "Clients deal directly with the advocate from the first document review through filing, hearing, and compliance, with clear updates at each stage.",
    ],
    handles: [
      "ROR (Record of Rights) and Adangal/Pahani corrections",
      "Mutation appeals and patta transfer disputes",
      "Tahsildar and MRO proceedings, and appeals to the RDO/Collector",
      "Encumbrance, boundary, and survey discrepancies",
      "Land acquisition objections and compensation matters",
      "Writs and revisions before the AP High Court on title and acquisition",
    ],
    forums: [
      "Tahsildar / MRO offices across Anantapur district",
      "Revenue Divisional Office (RDO)",
      "District Collector, Anantapur",
      "Andhra Pradesh High Court, Amaravati",
    ],
    faqs: [
      {
        q: "How do I correct a wrong entry in my Adangal or 1-B record?",
        a: "Corrections usually begin with an application to the Tahsildar/MRO supported by your sale deed, prior records, and survey documents. If rejected or delayed, the matter can be carried to the RDO or Collector, and in appropriate cases to the High Court. The right starting point depends on what the wrong entry is and how it was made.",
      },
      {
        q: "What documents should I bring for a land dispute consultation?",
        a: "Bring whatever you have — sale deed, pattadar passbook/title deed, Adangal/1-B extracts, encumbrance certificate, any notices or orders received, and prior case papers. Even partial documents help assess the correct forum and next step.",
      },
      {
        q: "Do you handle land matters outside Anantapur town?",
        a: `Yes. Advocate ${advocate} appears in revenue and land matters across Anantapur district, including Dharmavaram, before the relevant Tahsildar, RDO, and the AP High Court.`,
      },
      {
        q: "Can a revenue order be challenged in the High Court?",
        a: "In many situations, yes — through a writ petition or revision, depending on the order and the authority that passed it. Whether the High Court is the right forum, or whether a departmental appeal must come first, is assessed case by case.",
      },
    ],
    related: [
      "civil-lawyer-anantapur",
      "family-partition-lawyer-anantapur",
    ],
  },
  {
    slug: "civil-lawyer-anantapur",
    practiceId: "civil-contract",
    navLabel: "Civil & Contract",
    metaTitle: "Civil & Contract Lawyer in Anantapur",
    metaDescription:
      "Civil litigation advocate in Anantapur — recovery suits, specific performance, injunctions, declaratory relief, and contract disputes before the District Court and AP High Court.",
    h1: "Civil & Contract Litigation Lawyer in Anantapur",
    lead: "Drafting and contesting civil suits — recovery, specific performance, injunctions, and declaratory relief — before the District Court, Anantapur and the AP High Court.",
    body: [
      "Civil disputes are won on pleadings and documents. Suits are drafted with the facts arranged for hearing clarity, and contested with thorough documentary preparation rather than adjournment-driven delay.",
      `Advocate ${advocate} handles breach of contract and recovery of dues, suits for specific performance of agreements of sale, permanent and temporary injunctions, and declaratory relief — at trial and on appeal before the Andhra Pradesh High Court.`,
      "Where a dispute overlaps with property or revenue records, the civil strategy is coordinated with the correct revenue forum so relief is not lost on a procedural technicality.",
    ],
    handles: [
      "Recovery of money and breach-of-contract suits",
      "Specific performance of agreements of sale",
      "Permanent and temporary injunctions",
      "Declaratory relief and title declarations",
      "Civil appeals and revisions before the AP High Court",
    ],
    forums: [
      "District Court, Anantapur",
      "Junior & Senior Civil Judge Courts",
      "Andhra Pradesh High Court, Amaravati",
    ],
    faqs: [
      {
        q: "What is the time limit to file a recovery or contract suit?",
        a: "Limitation periods vary by the type of claim — recovery, specific performance, and declaratory suits each have their own limitation under the Limitation Act. Because delay can defeat an otherwise strong claim, it is best to get the documents reviewed early.",
      },
      {
        q: "Can I get an injunction to stop someone interfering with my property?",
        a: "A temporary injunction can be sought along with the main suit where there is a prima facie case, balance of convenience, and risk of irreparable injury. The supporting documents and the wording of the relief matter a great deal.",
      },
      {
        q: "Do you take civil appeals to the High Court?",
        a: `Yes. Advocate ${advocate} appears in civil appeals and revisions before the Andhra Pradesh High Court at Amaravati, in addition to trial work at the District Court, Anantapur.`,
      },
    ],
    related: [
      "revenue-land-lawyer-anantapur",
      "consumer-case-lawyer-anantapur",
    ],
  },
  {
    slug: "bail-criminal-lawyer-anantapur",
    practiceId: "bail-criminal",
    navLabel: "Bail & Criminal",
    metaTitle: "Bail & Criminal Lawyer in Anantapur",
    metaDescription:
      "Bail and criminal defence advocate in Anantapur — regular and anticipatory bail, quashing under S.482 CrPC, and trial defence before Sessions and Magistrate Courts. Urgent filing support.",
    h1: "Bail & Criminal Defence Lawyer in Anantapur",
    lead: "Regular and anticipatory bail, quashing petitions, and trial defence before the Sessions and Magistrate Courts — with urgent filing support and direct advocate communication.",
    body: [
      "Bail matters are time-sensitive. Applications for regular and anticipatory bail are prepared and moved promptly before the appropriate Sessions or Magistrate court, with the grounds tailored to the FIR, the sections invoked, and the stage of investigation.",
      `Advocate ${advocate} handles anticipatory bail, regular bail, quashing of proceedings under Section 482 CrPC, and defence at trial — with the client kept informed directly on hearing dates and likely next steps.`,
      "On urgent matters, the priority is to act quickly while keeping the application properly grounded, rather than filing in haste and weakening it.",
    ],
    handles: [
      "Anticipatory bail applications",
      "Regular bail before Sessions and Magistrate Courts",
      "Quashing of FIR/proceedings under Section 482 CrPC",
      "Trial defence and custody-related remedies",
      "Bail in cheque-bounce and property-related complaints",
    ],
    forums: [
      "Magistrate Courts, Anantapur",
      "Sessions Court, Anantapur",
      "Andhra Pradesh High Court, Amaravati",
    ],
    faqs: [
      {
        q: "What is the difference between regular bail and anticipatory bail?",
        a: "Anticipatory bail is sought before arrest, when a person apprehends arrest in a non-bailable case; regular bail is sought after arrest or surrender. Which applies depends on whether an arrest has already taken place and the sections invoked.",
      },
      {
        q: "How quickly can a bail application be filed?",
        a: "Urgent bail applications can be prepared and moved on a priority basis. The realistic timeline depends on the court, the case papers available, and the listing — these are discussed honestly at the outset.",
      },
      {
        q: "Can a false FIR be quashed?",
        a: "Proceedings can be challenged through a quashing petition under Section 482 CrPC in appropriate cases, for example where the allegations do not disclose an offence. Whether quashing is the right remedy is assessed on the FIR and material.",
      },
    ],
    related: [
      "family-partition-lawyer-anantapur",
      "consumer-case-lawyer-anantapur",
    ],
  },
  {
    slug: "family-partition-lawyer-anantapur",
    practiceId: "family-partition",
    navLabel: "Family & Partition",
    metaTitle: "Family & Partition Lawyer in Anantapur",
    metaDescription:
      "Family and property partition advocate in Anantapur — divorce, maintenance, custody, domestic violence remedies, and partition suits before the Family Court and District Court.",
    h1: "Family & Property Partition Lawyer in Anantapur",
    lead: "Divorce, maintenance, custody, domestic-violence remedies, and partition of ancestral and self-acquired property — before the Family Court and District Court, Anantapur.",
    body: [
      "Family matters need clear procedural guidance and steady representation. Mutual and contested divorce, maintenance and custody, and remedies under the Domestic Violence Act are handled with attention to both the law and the client's circumstances.",
      `Advocate ${advocate} also handles property partition suits — for ancestral and self-acquired property — where shares, possession, and title documents have to be established before the court.`,
      "Where a family dispute also involves land records or revenue entries, the partition strategy is coordinated with the correct revenue forum.",
    ],
    handles: [
      "Mutual-consent and contested divorce",
      "Maintenance under Section 125 CrPC and related provisions",
      "Child custody and guardianship",
      "Domestic Violence Act remedies",
      "Partition suits for ancestral and self-acquired property",
    ],
    forums: [
      "Family Court, Anantapur",
      "District Court, Anantapur",
      "Andhra Pradesh High Court, Amaravati",
    ],
    faqs: [
      {
        q: "How is ancestral property partitioned among family members?",
        a: "A partition suit establishes each co-owner's share and seeks division by metes and bounds. Title documents, the line of succession, and possession all matter. Many partition disputes also need revenue records to be set right.",
      },
      {
        q: "Can I claim maintenance for myself and my children?",
        a: "Maintenance can be sought under Section 125 CrPC and under personal law, depending on the circumstances. The claim is supported by proof of the relationship, the respondent's means, and the needs of those claiming.",
      },
      {
        q: "Do you handle mutual-consent divorce?",
        a: `Yes. Both mutual-consent and contested divorce are handled, with realistic guidance on timelines and on what the Family Court will require.`,
      },
    ],
    related: [
      "revenue-land-lawyer-anantapur",
      "civil-lawyer-anantapur",
    ],
  },
  {
    slug: "consumer-case-lawyer-anantapur",
    practiceId: "consumer-forums",
    navLabel: "Consumer Forums",
    metaTitle: "Consumer Case & Cheque Bounce Lawyer in Anantapur",
    metaDescription:
      "Consumer complaint and cheque-bounce advocate in Anantapur — deficiency of service complaints before District & State Consumer Commissions and S.138 NI Act cheque-bounce cases.",
    h1: "Consumer Forum & Cheque Bounce Lawyer in Anantapur",
    lead: "Consumer complaints, deficiency-of-service claims, and Section 138 cheque-bounce matters before the District and State Consumer Commissions and the Magistrate Courts.",
    body: [
      "Consumer and cheque-bounce matters reward focused pleadings and timely notice. Complaints for deficiency of service and unfair trade practice are drafted with the documents and timeline arranged clearly for the Commission.",
      `Advocate ${advocate} handles complaints before the District and State Consumer Disputes Redressal Commissions, and Section 138 Negotiable Instruments Act cheque-bounce cases — including the statutory notice and the complaint before the Magistrate.`,
      "Strict timelines apply to cheque-bounce notices and complaints, so early advice protects the claim.",
    ],
    handles: [
      "Deficiency-of-service and unfair-trade-practice complaints",
      "District and State Consumer Commission proceedings",
      "Section 138 NI Act cheque-bounce notices and complaints",
      "Appeals before the State Consumer Commission",
    ],
    forums: [
      "District Consumer Disputes Redressal Commission, Anantapur",
      "Andhra Pradesh State Consumer Commission",
      "Magistrate Courts, Anantapur (S.138 NI Act)",
    ],
    faqs: [
      {
        q: "What is the time limit to send a cheque-bounce notice?",
        a: "Under Section 138 of the Negotiable Instruments Act, a demand notice must be sent within 30 days of receiving the bank's cheque-return memo, and the complaint follows on a further statutory timeline. Because the limits are strict, act quickly once a cheque bounces.",
      },
      {
        q: "Where do I file a consumer complaint?",
        a: "The forum depends on the value of the claim — the District Consumer Commission for lower-value claims, and the State Commission above the prescribed limit. The correct forum is identified at the consultation.",
      },
      {
        q: "Can I claim compensation for poor service?",
        a: "A complaint for deficiency of service can seek refund, replacement, or compensation where a service has fallen short of what was promised. Supporting documents — bills, communications, and proof of the deficiency — strengthen the claim.",
      },
    ],
    related: [
      "civil-lawyer-anantapur",
      "bail-criminal-lawyer-anantapur",
    ],
  },
];

export const locationPages: LocationPage[] = [
  {
    slug: "anantapur",
    city: "Anantapur",
    metaTitle: "Advocate in Anantapur — Revenue, Civil, Criminal & Family Law",
    metaDescription:
      "Advocate S. Nagendra Naik in Anantapur — revenue & land, civil, criminal bail, family, partition, and consumer matters before the District Court, revenue offices, and AP High Court.",
    h1: "Advocate in Anantapur",
    lead: "Practising at the Anantapur Bar since 2018, with over 8 years of experience — revenue & land, civil, criminal, family, and consumer representation before the district's courts, revenue offices, and the AP High Court.",
    body: [
      `Advocate ${advocate} practises before the District Court at Anantapur, the Tahsildar, RDO and Collector offices for revenue and land matters, the Family Court, the Consumer Commission, and the Sessions and Magistrate courts — with appeals and writs before the Andhra Pradesh High Court at Amaravati.`,
      "Clients across Anantapur town and the surrounding mandals work directly with the advocate, from the first document review through filing, hearing, and compliance. The chamber is located at the District Court premises, Anantapur.",
    ],
    forums: [
      "District Court, Anantapur",
      "Tahsildar, RDO & Collector offices",
      "Family Court and Consumer Commission",
      "Sessions and Magistrate Courts",
      "Andhra Pradesh High Court, Amaravati",
    ],
    faqs: [
      {
        q: "Where is the chamber located in Anantapur?",
        a: `The chamber is at the District Court premises, Anantapur, Andhra Pradesh 515001. Call ${site.contact.phoneDisplay} to fix a time.`,
      },
      {
        q: "What types of cases are handled in Anantapur?",
        a: "Revenue and land disputes, civil litigation, criminal bail and defence, family and partition matters, and consumer/cheque-bounce cases — across the relevant courts and revenue forums.",
      },
    ],
  },
  {
    slug: "dharmavaram",
    city: "Dharmavaram",
    metaTitle: "Advocate for Dharmavaram — Land, Revenue & Civil Matters",
    metaDescription:
      "Legal representation for Dharmavaram — revenue & land disputes before the Tahsildar and RDO, civil, family, partition, and consumer matters, with AP High Court appeals.",
    h1: "Advocate for Dharmavaram Land & Revenue Matters",
    lead: "Revenue, land, civil, family, and consumer representation for clients in and around Dharmavaram — before the local revenue authorities and the courts at Anantapur and the AP High Court.",
    body: [
      `For clients in Dharmavaram, Advocate ${advocate} handles revenue and land record disputes before the Tahsildar/MRO and the Revenue Divisional Office, along with civil, family, partition, and consumer matters carried to the District Court at Anantapur and, where needed, the Andhra Pradesh High Court.`,
      "Land and Adangal corrections, mutations, and patta disputes around Dharmavaram are assessed on the records first, so the matter is filed in the correct forum at the correct stage.",
    ],
    forums: [
      "Tahsildar / MRO — Dharmavaram",
      "Revenue Divisional Office (RDO)",
      "District Court, Anantapur",
      "Andhra Pradesh High Court, Amaravati",
    ],
    faqs: [
      {
        q: "Do you handle Dharmavaram land matters before the local Tahsildar?",
        a: "Yes — ROR/Adangal corrections, mutations, and patta disputes are handled before the Dharmavaram Tahsildar and the RDO, with revisions or writs where the order needs to be challenged.",
      },
      {
        q: "Will I need to travel to Anantapur for my case?",
        a: `Revenue matters are heard locally, while civil and other court matters are at Anantapur. Much of the coordination is handled directly with the advocate — call ${site.contact.phoneDisplay} to discuss your situation.`,
      },
    ],
  },
];

export function getPracticePage(slug: string): PracticePage | undefined {
  return practicePages.find((p) => p.slug === slug);
}

export function getLocationPage(slug: string): LocationPage | undefined {
  return locationPages.find((p) => p.slug === slug);
}
